spring:
  profiles:
  active: dev # 激活开发环境配置
---
server:
  port: 6001 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: springcloud-config-eureka
eureka:
  instance:
    hostname: springcloud-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6001 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: springcloud-config-eureka
eureka:
  instance:
    hostname: springcloud-eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************