#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.zhrb.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
    application:profiles: dev # 开发环境
    name: springcloud-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://104.225.147.76:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据库名称
    username: cxyxqq
    password: Cxyxqq123!
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.zhrb.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  application:
    profiles: prod # 开发环境
    name: springcloud-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://104.225.147.76:3306/springcloud_db02?serverTimezone=GMT%2B8 # 数据库名称
    username: cxyxqq
    password: Cxyxqq123!
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    serviceUrl:
      registerWithEureka: true # 服务注册开关
      fetchRegistry: true # 服务发现开关
      defaultZone: http://127.0.0.1:6001/eureka/
      instance:
      instanceId: ${spring.application.name}:${server.port}-hystrix # 指定实例ID,就不会显示主机名了
      preferIpAddress: true #访问路径可以显示IP地址
