spring:
  profiles:
    active: dev # 激活开发环境配置
#idea下修改缩进
---
server:
  port: 5001 #端口号
spring:
  profiles: dev # 开发环境
    application:
      name: springcloud-config-dev
---
server:
  port: 5002 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: springcloud-config-prod
#保存时注意，选择 UTF-8 保存